# name: Vue.js build and deploy

# on:
#   push:
#     branches:
#       - nad-workflow

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run test:unit
#   test-coverage:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run test:coverage
#   lint:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run lint
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm ci
#     - run: npm run build
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - run: echo "ğŸ” Deployement"

# ---------------------------------------------------------------

# name: Vue.js build and deploy

# on:
#   push:
#     branches:
#       - nad-workflow

# jobs:
#   init:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run:  echo "ğŸ” Le pipline commence ici !"
#   test-unit:
#     needs: init
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run test:unit
#   test-coverage:
#     needs: init
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run test:coverage
#   lint:
#     needs: [init, test-unit, test-coverage]
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run lint
#   build:
#     needs: [init, test-unit, test-coverage, lint]
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm ci
#     - run: npm run build
#   deploy:
#     needs: [init, test-unit, test-coverage, lint]
#     runs-on: ubuntu-latest
#     steps:
#     - run: echo "ğŸ” Deployement"
#   fin:
#     needs: [init, test-unit, test-coverage, lint, build, deploy]
#     runs-on: ubuntu-latest
#     steps:
#     - run: echo "ğŸ” Le pipeline se termine ici"

# ----------------------------------------------

# EXO 1
# name: Vue.js build and deploy

# on:
#   push:
#     branches:
#       - nad-workflow

# jobs:
#   init:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run:  echo "ğŸ” Le pipline commence ici !"
#   a:
#     needs: init
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run test:unit
#   b:
#     needs: init
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run test:coverage
#   c:
#     needs: init
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run test:coverage
#   d:
#     needs: init
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run test:coverage
#   e:
#     needs: [init, a,b,c,d]
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run lint
#   f:
#     needs: [init, a,b,c,d]
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run lint
#   build:
#     needs: [init, a, b, c, d ,e, f ]
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm ci
#     - run: npm run build
#   deploy:
#     needs: [init, a, b, c, d ,e, f, build, ]
#     runs-on: ubuntu-latest
#     steps:
#     - run: echo "ğŸ” Deployement"
#   fin:
#     needs: [init,  a, b, c, d ,e, f, build, deploy]
#     runs-on: ubuntu-latest
#     steps:
#     - run: echo "ğŸ” Le pipeline se termine ici"

# -------------------------------------------------------------

# EXO 2
# name: Vue.js build and deploy

# on:
#   push:
#     branches:
#       - nad-workflow

# jobs:
#   init:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run:  echo "ğŸ” Le pipline commence ici !"
#   a:
#     needs: init
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run test:unit
#   b:
#     needs: init
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run test:coverage
#   c:
#     needs: [init, a,b]
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run test:coverage
#   d:
#     needs: [init, a,b]
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run test:coverage
#   e:
#     needs: [init, a,b,c,d]
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run lint
#   f:
#     needs: [init, a,b,c,d,e]
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run lint
#   g:
#     needs: [init, a,b,c,d,e]
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm install
#     - run: npm run lint
#   build:
#     needs: [init, a, b, c, d ,e, f ,g]
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 16.x
#     - run: npm ci
#     - run: npm run build
#   deploy:
#     needs: [init, a, b, c, d ,e, f, g, build, ]
#     runs-on: ubuntu-latest
#     steps:
#     - run: echo "ğŸ” Deployement"
#   fin:
#     needs: [init,  a, b, c, d ,e, f, g, build, deploy]
#     runs-on: ubuntu-latest
#     steps:
#     - run: echo "ğŸ” Le pipeline se termine ici"

# ----------------------------------------------------------------------

# EXO 3
name: Vue.js build and deploy

on:
  push:
    branches:
      - nad-workflow

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run:  echo "ğŸ” Le pipline commence ici !"
  a:
    needs: init
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run test:unit
  b:
    needs: init
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run test:coverage
  c:
    needs: init
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run test:coverage
  d:
    needs: init
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run test:coverage
  e:
    needs: init
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run lint
  f:
    needs: init
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run lint
  g:
    needs: init
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run lint
  build:
    needs: [init, a, b, c, d ,e, f ,g]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm ci
    - run: npm run build
  deploy:
    needs: [init, a, b, c, d ,e, f, g, build, ]
    runs-on: ubuntu-latest
    steps:
    - run: echo "ğŸ” Deployement"
  fin:
    needs: [init,  a, b, c, d ,e, f, g, build, deploy]
    runs-on: ubuntu-latest
    steps:
    - run: echo "ğŸ” Le pipeline se termine ici"